empno=input("EmpNo: ")
empname=input("EmpName: ")
address=input("Address: ")
city=input("City: ")
phone_no=input("PhoneNo: ")
f=open("21082024/empData1.txt",'w')

f.write("EmpNo: "+empno)
f.write("\nEmpName: "+empname)
f.write("\nAddress: "+address)
f.write("\nCity: "+city)
f.write("\nPhoneNo: "+phone_no)
f.close()