empno=input("EmpNo: ")
empname=input("EmpName: ")
address=input("Address: ")
city=input("City: ")
phone_no=input("PhoneNo: ")
f=open("21082024/empData1.xls",'a')

f.write("\nEmpNo: \t"+empno)
f.write("\nEmpName: \t"+empname)
f.write("\nAddress: \t"+address)
f.write("\nCity: \t"+city)
f.write("\nPhoneNo: \t"+phone_no)
f.close()